### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by mikecx** [janklimo/shrine-cloudimage#9]
Using the following documentation section:

```ruby
require 'cloudimage'

Shrine.plugin :cloudimage, Cloudimage::Client.new(
  token: 'token', salt: 'salt', sign_urls: false, signature_length: 10
)
```

results in the following error: `ArgumentError: wrong number of arguments (given 2, expected 1)`

By either using the first option or adding `client:` before the Cloudimage Client creation, appears to work as expected.

i.e.

```ruby
require 'cloudimage'

Shrine.plugin :cloudimage, client: Cloudimage::Client.new(
  token: 'token', salt: 'salt', sign_urls: false, signature_length: 10
)
```

**Comment by janklimo** [comment]
Thank you @mikecx yup, that's the correct usage, as you can see in the spec:

https://github.com/janklimo/shrine-cloudimage/blob/e351151bf29d9c5c68e1400c1c9c7679a5872ef9/spec/shrine/plugins/cloudimage_spec.rb#L28-L35

Fixed 👍
